In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

os.makedirs("data/raw", exist_ok=True)
os.makedirs("data/processed", exist_ok=True)

In [3]:
data = {
    "date": [
        "2024-01-01","2024-01-02","2024-01-03",
        "2024-01-04","2024-01-05","2024-01-06"
    ],
    "product": [
        "Notebook","Mouse","Teclado",
        "Notebook","Mouse","Monitor"
    ],
    "category": [
        "Eletronicos","Eletronicos","Eletronicos",
        "Eletronicos","Eletronicos","Eletronicos"
    ],
    "price": [3500, 80, 150, 3400, 90, 1200],
    "quantity": [2,5,3,1,6,2],
    "city": [
        "São Paulo","Rio de Janeiro","Belo Horizonte",
        "São Paulo","Curitiba","Rio de Janeiro"
    ]
}

In [4]:
# Isso cria a tabela.

df = pd.DataFrame(data)

df

         date   product     category  price  quantity            city
0  2024-01-01  Notebook  Eletronicos   3500         2       São Paulo
1  2024-01-02     Mouse  Eletronicos     80         5  Rio de Janeiro
2  2024-01-03   Teclado  Eletronicos    150         3  Belo Horizonte
3  2024-01-04  Notebook  Eletronicos   3400         1       São Paulo
4  2024-01-05     Mouse  Eletronicos     90         6        Curitiba
5  2024-01-06   Monitor  Eletronicos   1200         2  Rio de Janeiro

In [5]:
df.to_csv("data/raw/vendas.csv", index=False)

In [6]:
# Isso é o E do ETL (Extract).

df_raw = pd.read_csv("data/raw/vendas.csv")

df_raw.head()

         date   product     category  price  quantity            city
0  2024-01-01  Notebook  Eletronicos   3500         2       São Paulo
1  2024-01-02     Mouse  Eletronicos     80         5  Rio de Janeiro
2  2024-01-03   Teclado  Eletronicos    150         3  Belo Horizonte
3  2024-01-04  Notebook  Eletronicos   3400         1       São Paulo
4  2024-01-05     Mouse  Eletronicos     90         6        Curitiba

In [7]:
# Isso mostra: tipos das colunas, quantidade de valores, se existem dados faltantes

df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      6 non-null      object
 1   product   6 non-null      object
 2   category  6 non-null      object
 3   price     6 non-null      int64
 4   quantity  6 non-null      int64
 5   city      6 non-null      object
dtypes: int64(2), object(4)
memory usage: 420.0+ bytes

In [8]:
# Isso mostra estatísticas das colunas numéricas:
# média, mínimo, máximo, desvio padrão
df_raw.describe()

             price  quantity
count     6.000000  6.000000
mean   1403.333333  3.166667
std    1641.397778  1.940790
min      80.000000  1.000000
25%     105.000000  2.000000
50%     675.000000  2.500000
75%    2850.000000  4.500000
max    3500.000000  6.000000

In [9]:
# Isso mostra quantos valores faltando existem em cada coluna.
df_raw.isnull().sum()

date        0
product     0
category    0
price       0
quantity    0
city        0
dtype: int64

In [10]:
# Isso converte a coluna para datetime

df = df_raw.copy()

df["date"] = pd.to_datetime(df["date"])

df.head()

        date   product     category  price  quantity            city
0 2024-01-01  Notebook  Eletronicos   3500         2       São Paulo
1 2024-01-02     Mouse  Eletronicos     80         5  Rio de Janeiro
2 2024-01-03   Teclado  Eletronicos    150         3  Belo Horizonte
3 2024-01-04  Notebook  Eletronicos   3400         1       São Paulo
4 2024-01-05     Mouse  Eletronicos     90         6        Curitiba

In [11]:
# faturamento = price * quantity

df["revenue"] = df["price"] * df["quantity"]

df.head()

        date   product     category  price  quantity            city  revenue
0 2024-01-01  Notebook  Eletronicos   3500         2       São Paulo     7000
1 2024-01-02     Mouse  Eletronicos     80         5  Rio de Janeiro      400
2 2024-01-03   Teclado  Eletronicos    150         3  Belo Horizonte      450
3 2024-01-04  Notebook  Eletronicos   3400         1       São Paulo     3400
4 2024-01-05     Mouse  Eletronicos     90         6        Curitiba      540

In [12]:
# Criar colunas de tempo , ano, mês e dia

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

df.head()

,date,product,category,price,quantity,city,revenue,year,month,day
0,2024-01-01,Notebook,Eletronicos,3500,2,São Paulo,7000,2024,1,1
1,2024-01-02,Mouse,Eletronicos,80,5,Rio de Janeiro,400,2024,1,2
2,2024-01-03,Teclado,Eletronicos,150,3,Belo Horizonte,450,2024,1,3
3,2024-01-04,Notebook,Eletronicos,3400,1,São Paulo,3400,2024,1,4
4,2024-01-05,Mouse,Eletronicos,90,6,Curitiba,540,2024,1,5

In [13]:
df.to_csv("data/processed/vendas_tratadas.csv", index=False)

In [14]:
import os

os.listdir("data/processed")

['vendas_tratadas.csv']